### ISSUE TITLE
Contact/H-bond matrix 

### ISSUE THREAD

**Issue by DipBobDar** [djmaity/md-davis#7]
* MD DaVis version:0.4.1
* Python version: 3.11.5
* Operating System:Linux
NAME="openSUSE Leap"
VERSION="15.4"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.4"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"

### Description

I wanted to get the hmbond map 

### What I Did

I wanted to get hbond plot using md davis but is not able to proceed because they can not regonize the .gro file given by -S command in the following commands

(md-davis) > md-davis hbond -x hb_matrix.xpm --index_file hb_index.ndx -s MD.gro --save_pickle hb_data.p -g hbonds_Protein
Traceback (most recent call last):
  File "/home/ddhar/anaconda3/envs/md-davis/bin/md-davis", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ddhar/anaconda3/envs/md-davis/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddhar/anaconda3/envs/md-davis/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ddhar/anaconda3/envs/md-davis/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddhar/anaconda3/envs/md-davis/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddhar/anaconda3/envs/md-davis/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddhar/anaconda3/envs/md-davis/lib/python3.11/site-packages/md_davis/hbond.py", line 363, in main
    molecular_contacts = Hbonds(structure)
                         ^^^^^^^^^^^^^^^^^
  File "/home/ddhar/anaconda3/envs/md-davis/lib/python3.11/site-packages/md_davis/hbond.py", line 277, in __init__
    self.structure = PandasPdb().read_pdb(structure)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddhar/anaconda3/envs/md-davis/lib/python3.11/site-packages/biopandas/pdb/pandas_pdb.py", line 94, in read_pdb
    self.pdb_path, self.pdb_text = self._read_pdb(path=path)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddhar/anaconda3/envs/md-davis/lib/python3.11/site-packages/biopandas/pdb/pandas_pdb.py", line 312, in _read_pdb
    raise ValueError(
ValueError: Wrong file format; allowed file formats are .pdb, .pdb.gz, .ent, .ent.gz

Please help me to resolve this

**Comment by djmaity** [comment]
@DipBobDar You are right. The `md-davis hbond` command uses the [biopandas](https://github.com/BioPandas/biopandas) package to read the structure file, which only supports  .pdb, .pdb.gz, .ent, .ent.gz file formats. I shall update the code to support .gro files. In the meantime, please provide a PDB file to `md-davis hbond`. You can use [`gmx trjconv`](https://manual.gromacs.org/current/onlinehelp/gmx-trjconv.html) to get a PDB file from the .tpr file used for the simulation and `gmx hbond` calculation:
`gmx trjconv -f trajectory.trr -s stucture.tpr -o output.pdb -dump 0`

Thank you for the question. I have updated the documentation to clarify this.
